# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 296dd419d28c561b0d65db8f8bff47c08bbab0b48f92a062d12899b50cee69417514a2ac4f76341826615cae96d2975223d447d2a41ede53788e11b730bf7761

test:
  secret_key_base: a71aa265e97ede0f47c3ef475c48943da7438462c16176ed7a7baa458d5d7b6afa2682da93c80814867212c12a13f6011cd6673e1607a455f11649b8423377f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
